services:
  mariadb10:
    image: mariadb:10.11
    container_name: mariadb10
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Seoul"
      MYSQL_ROOT_PASSWORD: "mystrongpassword!"
      MARIADB_CHARACTER_SET_SERVER: "utf8mb4"
      MARIADB_COLLATION_SERVER: "utf8mb4_general_ci"
    volumes:
      - ./data:/var/lib/mysql
      - ./my-cdc.cnf:/etc/mysql/conf.d/my-cdc.cnf:ro
    restart: on-failure:3
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" || exit 1']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s
